# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH
export GOROOT=/root/.gvm/gos/go1.5
export GOROOT_BOOTSTRAP=$GOROOT
export PATH=$PATH:$GOROOT/bin
