nginx:
  build: containers/nginx
  ports:
    - '8080:80'
  volumes_from:
    - datastore
  links:
    - web-app

web-app:
  build: .
  ports:
    - '8000:8000'
  volumes_from:
    - datastore

datastore:
  build: containers/datastore
